name: Rails project test suite

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:11
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v1
    - name: Set up RVM
      run: curl -sSL https://get.rvm.io | bash
    - name: Set up Ruby, install dependencies and run tests
      env:
        PGHOST: localhost
        PGUSER: postgres
        RAILS_ENV: test
      run: |
        source $HOME/.rvm/scripts/rvm
        rvm install 2.5.6
        rvm --default use 2.5.6
        gem install bundler
        sudo apt-get -yqq install libpq-dev
        bundle install --jobs 4 --retry 3
        bundle exec rails db:create
        bundle exec rails db:migrate
        bundle exec rspec
